create database BUDGET_DB;
use BUDGET_DB;

create table PERSON (
	PERSON_ID Integer AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PASSWORT VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	IS_ADMIN BIT NOT NULL
);

create table TYP (
	TYP_ID Integer AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	MULTIPLIKATOR Integer NOT NULL
);

create table INTERVALL ( 
	INTERVALL_ID Integer AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	TAGE Integer NOT NULL
);

create table ZYKLUS (
	ZYKLUS_ID Integer AUTO_INCREMENT PRIMARY KEY,
	TAGE Bit(7),
	UNTERBRUCH Integer,
	INTERVALL_ID Integer NOT NULL,
	FOREIGN KEY (INTERVALL_ID) REFERENCES INTERVALL(INTERVALL_ID)
);

create table DAUERAUFTRAG (
	DAUERAUFTRAG_ID Integer AUTO_INCREMENT PRIMARY KEY,
	MENGE DOUBLE NOT NULL,
	START_DATUM DATE NOT NULL,
	END_DATUM DATE,
	TYP_ID Integer NOT NULL,
	ZYKLUS_ID Integer NOT NULL,
	PERSON_ID Integer NOT NULL,
	FOREIGN KEY (TYP_ID) REFERENCES TYP(TYP_ID),
	FOREIGN KEY (ZYKLUS_ID) REFERENCES ZYKLUS(ZYKLUS_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
	
);

create table BUDGET (
	BUDGET_ID Integer AUTO_INCREMENT PRIMARY KEY,
	MENGE DOUBLE NOT NULL,
	DATUM DATE NOT NULL,
	TYP_ID Integer NOT NULL,
	PERSON_ID Integer NOT NULL,
	FOREIGN KEY (TYP_ID) REFERENCES TYP(TYP_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
	
);

